### ISSUE TITLE
webview.devtools crashes fresh Windows 7

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint-chromium#12]
I started up a virtual machine of Windows 7 with nothing on it but Tint, VC Redist, and .NET Framework installed.
Everything seems to work for the most part in my tests so far, but ``webview.devtools = true;`` causes a crash for some reason. I don't have this problem on my actual development machine however. Any insight?

**Comment by trevorlinton** [comment]
@JohnLouderback Take a look at whats in your package, there must be a file called devtools_resources.pak. If its not there the dev tools will crash on load.

**Comment by trevorlinton** [comment]
@JohnLouderback We discovered a race condition with CefSharp that was causing the crash (for many other things it would simply cause Cef to stop working which may have been related to another bug you had encountered).  This should be fixed with the latest commit.  Closing this out, if you still have issues please feel free to reopen this.
